# git-cliff ~ configuration file

[remote.github]
owner = "winksaville"
repo = "rp-hal"
# token = ""

[changelog]
# template for the changelog header
header = """
<!-- header cliff.version.commits.toml -->
"""

# template for the changelog body:
body = """
## What's Changed
{% if version %}'{{ version }}'{% endif %}
{% for commit in commits %}
  {%- if commit.remote.username -%}
     -1 remote.username='{{ commit.remote.username }}'
  {%- endif -%}
  * conventional={{ commit.conventional }} id='{{ commit.id }}'
{% endfor %}
"""
# remove the leading and trailing whitespace from the template
trim = true

# template for the changelog footer
footer = """
<!-- footer cliff.version.commits.toml -->
"""

# postprocessors
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
#commit_preprocessors = [
#  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
#]
filter_commits = false
topo_order = false
sort_commits = "newest"

[bump]
initial_tag = "rp235x-hal-v0.2.0"
